[package]
name = "doria-rt"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "doria_rt"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[features]
default = ["standalone-windows-support"]
standalone-windows-support = []

[dependencies]
doria-diagnostic-catalogue = { path = "../doria-diagnostic-catalogue" }
doria-unicode = { path = "../doria-unicode" }
ryu.workspace = true
unicode-width = { version = "=0.2.2", default-features = false, features = ["cjk", "no_std"] }
